### ISSUE TITLE
regxmllib assumes that identifiers for MetaDefinitions are always ULs

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#69] opened 2015-08-26 18:57 UTC
Various parts of the code indicate this and warning messages such as the following provide further evidence for this:

```
WARNING: Unknown property UL = urn:smpte:ul:a0240060.94eb75cb.ce2aca4f.51ab11d3 at group CDCIDescriptor
```

(In this example this is not a UL but an AUID containing the value of the UUID 'ce2aca4f-51ab-11d3-a024-006094eb75cb')

Identifiers for MetaDefinitions (Groups, Types, Elements, Labels) are actually AUIDs:
- Refer to the ST 2001-1 XSDs
- Refer to ST 2001-1 Section 6.1:

>  Identification: an AUID that uniquely identifies the definitions. 
- As per ST 377-1, each entry in the Primer Pack consists of both a "Local Tag" (UInt16) and a "UID" (AUID)

ST 336 is clear that the KLV key must be a 16-byte SMPTE UL but in reality (given the above and looking at some real files) the KLV Key can actually be an AUID (and so can encode the value of a UUID). Example of an UUID-encoded-as-an-AUID used as a KLV Key:

```
WARNING: Failed to read Group: urn:smpte:ul:80530800.36210804.b3b398a5.1c9011d4
```

**Comment by palemieux** [comment] 2016-08-24 03:43
@thomasheritage So is the issue that the error reporting should differentiate between UUID and UL?

**Comment by thomasheritage** [comment] 2016-08-24 11:00
I think that it goes deeper than that. I believe (but haven't looked at the details of this for about a year...) that the code assumes that identifiers for MetaDefinitions are ULs but infact they are AUIDs (which is a superset of UL and UUID -- with some byte re-ordering). Therefore, I think that to be able to properly cope with any permitted MetaDefinition the IDs of MetaDefinitions (at all points in the code) need to be modelled as AUIDs rather than ULs.

**Comment by palemieux** [comment] 2016-08-24 19:35
Ok. So:

- the metadictionary should use AUID. No UUID should however show up if the metadictionary is created from the metadata registers.
- the fragment generator should accept AUID for Key values from the MXF file, even though, technically, only ULs are permitted

Right?

**Comment by thomasheritage** [comment] 2016-09-02 15:24
> the metadictionary should use AUID. No UUID should however show up if the metadictionary is created from the metadata registers.

Sounds OK

> the fragment generator should accept AUID for Key values from the MXF file

Sounds OK

> even though, technically, only ULs are permitted

Sounds basically right but at least in the Primer Pack it seems that AUIDs are allowed. Anyway, in reality we will see some files that use AUIDs that are not ULs (I think there are probably some examples in those files with the "indirect" types that you were developing against a few months ago).

**Comment by palemieux** [comment] 2019-08-03 04:03
@thomasheritage Was https://github.com/sandflow/regxmllib/issues/104 a duplicate of this issue, and https://github.com/sandflow/regxmllib/commit/940d358383f70f4bfef3b548c7f569bbe71e4dc4 closed it? Perhaps you have a sample file that can be added to the unit tests? 

Apologies for the trip down memory lane.

**Comment by thomasheritage** [comment] 2019-09-08 12:49
I tried a [recent jar file](https://repo1.maven.org/maven2/com/sandflow/regxmllib/1.1.3/regxmllib-1.1.3.jar) with [indirect.mxf](https://github.com/sandflow/regxmllib/blob/master/src/test/resources/mxf-files/indirect.mxf) and compared the output to an "old" version of the jar file (from 2017 some time I think).

I now see statements like:
```
INFO: com.sandflow.smpte.regxml.FragmentBuilder.EventCodes::UNKNOWN_PROPERTY Unknown property urn:uuid:ce2aca4f-51ab-11d3-a024-006094eb75cb at Group CDCIDescriptor
```

instead of:
```
INFO: Unknown property UL = urn:smpte:ul:a0240060.94eb75cb.ce2aca4f.51ab11d3 at group CDCIDescriptor
```

So, my conclusion is that this issue is probably fixed and so could be closed.

Great to see these improvements to regxmllib -- thanks for picking up on these old issues.

**Closed** 2019-09-08 15:47 UTC
Labels: enhancement
