### ISSUE TITLE
dupIndexEntryArray1

### ISSUE THREAD

**Issue by thomasheritage** [sandflow/regxmllib#23] opened 2015-01-20 15:46 UTC
I used smpte_registers-bbc_rd_db_exports-201412092156 and generated www-smpte-ra-org-reg-2003-2012.xml

In this I see:

```
<TypeDefinitionVariableArray>
<Identification>urn:smpte:ul:060e2b34.01040101.04020700.00000000</Identification>
<Symbol>dupIndexEntryArray1</Symbol>
<Name>IndexEntryArray</Name>
<ElementType>urn:smpte:ul:060e2b34.01040101.04100600.00000000</ElementType>
</TypeDefinitionVariableArray>
```

Why has the symbol changed from what is in Groups.xml (i.e. "IndexEntryArray")?

**Comment by palemieux** [comment] 2015-01-20 19:07
This was caused by a bug that checked for duplicate symbols without including the register namespace.

Should be fixed.

**Closed by palemieux** 2015-01-20 19:07 UTC
